chunking_config:
  chunk_overlap_tokens: 32
  chunk_size_tokens: 64
  class_path: cookbook.config.data_pipeline.recursive_text_splitter.RecursiveTextSplitterChunkingConfig
  embedding_model_endpoint: databricks-gte-large-en
class_path: cookbook.config.data_pipeline.DataPipelineConfig
output:
  chunked_docs_table: mlops_pj.hackathon.medicine_leaflets_chunked
  class_path: cookbook.config.data_pipeline.data_pipeline_output.DataPipelineOuputConfig
  parsed_docs_table: mlops_pj.hackathon.medicine_leaflets
  vector_index: mlops_pj.hackathon.medicine_leaflets_chunked_index
  vector_search_endpoint: one-env-shared-endpoint-11
source:
  class_path: cookbook.config.data_pipeline.uc_volume_source.UCVolumeSourceConfig
  uc_catalog_name: mlops_pj
  uc_schema_name: hackathon
  uc_volume_name: leaflets
  volume_path: /Volumes/mlops_pj/hackathon/leaflets
  volume_uc_fqn: mlops_pj.hackathon.leaflets
