class_path: cookbook.config.data_pipeline.uc_volume_source.UCVolumeSourceConfig
uc_catalog_name: workspace
uc_schema_name: shared
uc_volume_name: leaflets
volume_path: /Volumes/workspace/shared/leaflets
volume_uc_fqn: workspace.shared.leaflets
